
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200


#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200


#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200

#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
#TEST vers une uri aliasant un directory sans index ni autoindex
GET http://localhost:8080/toto
HTTP 200
